<Project>
  <Import Project="$(MSBuildThisFileDirectory)build/Version.props" />
  <Import Project="$(MSBuildThisFileDirectory)build/Common.props" />
  <Import Project="$(MSBuildThisFileDirectory)build/PackageMetaInfo.props" />
  <Import Project="$(MSBuildThisFileDirectory)build/Output.props" />
</Project>
