<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AtomUI.Cli.Tests</AssemblyName>
    <RootNamespace>AtomUI.Cli.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/AtomUI.Cli.Abstractions/AtomUI.Cli.Abstractions.csproj" />
    <ProjectReference Include="../../src/AtomUI.Cli.Modularity/AtomUI.Cli.Modularity.csproj" />
    <ProjectReference Include="../../src/AtomUI.Cli.Hosting/AtomUI.Cli.Hosting.csproj" />
    <ProjectReference Include="../../src/AtomUI.Cli/AtomUI.Cli.csproj" />
    <ProjectReference Include="../../tools/AtomUI.Cli.MetadataBuilder/AtomUI.Cli.MetadataBuilder.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
</Project>
