using System.Text;

namespace AtomUI.Cli.MetadataBuilder.SourceAnalysis.Writers;

internal static class CatalogSnapshotCodeWriter
{
    public static void Write(ExtractedCatalogSnapshot snapshot, string outputPath)
    {
        var directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(outputPath, Generate(snapshot), Encoding.UTF8);
    }

    private static string Generate(ExtractedCatalogSnapshot snapshot)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace AtomUI.Cli.Hosting.Metadata;");
        builder.AppendLine();
        builder.AppendLine("internal static class BuiltInMetadataCatalogFactory");
        builder.AppendLine("{");
        builder.AppendLine("    public static MetadataCatalog Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        return new MetadataCatalog(");
        builder.AppendLine($"            {S(snapshot.SchemaVersion)},");
        builder.AppendLine($"            {S(snapshot.TargetVersion)},");
        builder.AppendLine($"            {S(snapshot.SourceCommit)},");
        AppendProducts(builder, snapshot.Products);
        AppendPackages(builder, snapshot.Packages);
        AppendCategories(builder, snapshot.Categories);
        AppendControls(builder, snapshot.Controls);
        builder.AppendLine("            [],");
        builder.AppendLine("            [],");
        AppendDocuments(builder, snapshot.Documents);
        builder.AppendLine("            [],");
        AppendChangelog(builder, snapshot.Changelog, closeCatalog: true);
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendProducts(StringBuilder builder, IReadOnlyList<ExtractedCatalogProduct> products)
    {
        builder.AppendLine("            [");
        foreach (var product in products)
        {
            builder.AppendLine($"                new ProductDescriptor({S(product.Id)}, {S(product.Name)}, {S(product.Description)}),");
        }

        builder.AppendLine("            ],");
    }

    private static void AppendPackages(StringBuilder builder, IReadOnlyList<ExtractedCatalogPackage> packages)
    {
        builder.AppendLine("            [");
        foreach (var package in packages)
        {
            builder.AppendLine("                new PackageDescriptor(");
            builder.AppendLine($"                    {S(package.Id)},");
            builder.AppendLine($"                    {S(package.ProductId)},");
            builder.AppendLine($"                    {S(package.Version)},");
            builder.AppendLine($"                    {S(package.Description)},");
            builder.AppendLine($"                    {SA(package.Controls)},");
            builder.AppendLine($"                    IsOptional: {B(package.IsOptional)},");
            builder.AppendLine($"                    IsCommercial: {B(package.IsCommercial)}),");
        }

        builder.AppendLine("            ],");
    }

    private static void AppendCategories(StringBuilder builder, IReadOnlyList<ExtractedCatalogCategory> categories)
    {
        builder.AppendLine("            [");
        foreach (var category in categories)
        {
            builder.AppendLine($"                new ControlCategoryDescriptor({S(category.Id)}, {S(category.Name)}, {S(category.RouteSegment)}, {category.DisplayOrder}),");
        }

        builder.AppendLine("            ],");
    }

    private static void AppendControls(StringBuilder builder, IReadOnlyList<ExtractedCatalogControl> controls)
    {
        builder.AppendLine("            [");
        foreach (var control in controls)
        {
            builder.AppendLine("                new ControlDescriptor(");
            builder.AppendLine($"                    {S(control.Name)},");
            builder.AppendLine($"                    {S(control.DisplayName)},");
            builder.AppendLine($"                    {S(control.ProductId)},");
            builder.AppendLine($"                    {S(control.PackageId)},");
            builder.AppendLine($"                    {S(control.Namespace)},");
            builder.AppendLine($"                    {S(control.GalleryRoute)},");
            builder.AppendLine($"                    {S(control.Description)},");
            builder.AppendLine($"                    {S(control.CategoryId)},");
            builder.AppendLine($"                    {S(control.CategoryName)},");
            builder.AppendLine($"                    {control.DisplayOrder},");
            builder.AppendLine($"                    {B(control.IsCommercial)},");
            builder.AppendLine($"                    {B(control.IsOptionalPackage)},");
            builder.AppendLine($"                    {B(control.IsHidden)}),");
        }

        builder.AppendLine("            ],");
    }

    private static void AppendDocuments(StringBuilder builder, IReadOnlyList<ExtractedCatalogDocument> documents)
    {
        builder.AppendLine("            [");
        foreach (var document in documents)
        {
            builder.AppendLine($"                new DocumentDescriptor({S(document.Kind)}, {S(document.TargetId)}, {S(document.Title)}, {S(document.Markdown)}),");
        }

        builder.AppendLine("            ],");
    }

    private static void AppendChangelog(
        StringBuilder builder,
        IReadOnlyList<ExtractedCatalogChangelogEntry> changelog,
        bool closeCatalog)
    {
        builder.AppendLine("            [");
        foreach (var entry in changelog)
        {
            builder.AppendLine($"                new ChangelogEntryDescriptor({S(entry.Version)}, {S(entry.TargetKind)}, {S(entry.TargetId)}, {S(entry.Severity)}, {S(entry.Message)}),");
        }

        builder.Append(closeCatalog ? "            ]);" : "            ],");
        builder.AppendLine();
    }

    private static string S(string value)
    {
        return SymbolDisplayStringLiteral(value);
    }

    private static string SA(IReadOnlyList<string> values)
    {
        return values.Count == 0
            ? "[]"
            : $"[{string.Join(", ", values.Select(S))}]";
    }

    private static string B(bool value)
    {
        return value ? "true" : "false";
    }

    private static string SymbolDisplayStringLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var ch in value)
        {
            builder.Append(ch switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\r' => "\\r",
                '\n' => "\\n",
                '\t' => "\\t",
                _ => ch
            });
        }

        builder.Append('"');
        return builder.ToString();
    }
}
