using System.Text;

namespace AtomUI.Cli.MetadataBuilder.SourceAnalysis.Writers;

internal static class DocumentSnapshotCodeWriter
{
    public static void Write(ExtractedDocumentSnapshot snapshot, string outputPath)
    {
        var directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(outputPath, Generate(snapshot), Encoding.UTF8);
    }

    private static string Generate(ExtractedDocumentSnapshot snapshot)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine();
        builder.AppendLine("namespace AtomUI.Cli.Hosting.Metadata;");
        builder.AppendLine();
        builder.AppendLine("internal static class BuiltInDocumentSnapshotFactory");
        builder.AppendLine("{");
        builder.AppendLine("    public static System.Collections.Generic.IReadOnlyList<DocumentSnapshot> Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        var source = new DocumentSourceIdentity(");
        builder.AppendLine($"            {S(snapshot.Source.SourceRootConvention)},");
        builder.AppendLine($"            {S(snapshot.Source.SourceRef)},");
        builder.AppendLine($"            {S(snapshot.Source.SourceCommit)},");
        builder.AppendLine($"            {S(snapshot.Source.GeneratedAt)});");
        builder.AppendLine();
        builder.AppendLine("        return new DocumentSnapshot[]");
        builder.AppendLine("        {");
        builder.AppendLine("            new DocumentSnapshot(");
        builder.AppendLine($"                {S(snapshot.SchemaVersion)},");
        builder.AppendLine($"                {S(snapshot.SnapshotId)},");
        builder.AppendLine($"                {S(snapshot.TargetVersion)},");
        builder.AppendLine($"                {S(snapshot.ProductId)},");
        builder.AppendLine($"                {S(snapshot.PackageId)},");
        builder.AppendLine($"                {S(snapshot.Language)},");
        builder.AppendLine("                source,");
        builder.AppendLine("                new ControlDocument[]");
        builder.AppendLine("                {");
        foreach (var control in snapshot.Controls)
        {
            AppendControl(builder, control);
        }

        builder.AppendLine("                },");
        builder.AppendLine("                new TopicDocument[]");
        builder.AppendLine("                {");
        foreach (var topic in snapshot.Topics)
        {
            AppendTopic(builder, topic);
        }

        builder.AppendLine("                }),");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendControl(StringBuilder builder, ExtractedControlDocument control)
    {
        builder.AppendLine("                    new ControlDocument(");
        builder.AppendLine($"                        {S(control.Id)},");
        builder.AppendLine($"                        {S(control.Name)},");
        builder.AppendLine($"                        {S(control.DisplayName)},");
        builder.AppendLine($"                        {S(control.CategoryId)},");
        builder.AppendLine($"                        {S(control.ProductId)},");
        builder.AppendLine($"                        {S(control.PackageId)},");
        builder.AppendLine($"                        {B(control.IsCommercial)},");
        builder.AppendLine($"                        {S(control.Status)},");
        builder.AppendLine($"                        {S(control.Summary)},");
        AppendIdentity(builder, control.Identity, "                        ");
        AppendUsage(builder, control.Usage, "                        ");
        AppendApiSurface(builder, control.ApiSurface, "                        ");
        AppendLogic(builder, control.LogicStructure, "                        ");
        AppendTheme(builder, control.Theme, "                        ");
        AppendExamples(builder, control.Examples, "                        ");
        AppendTokens(builder, control.Tokens, "                        ");
        AppendSemanticParts(builder, control.SemanticParts, "                        ");
        AppendSourceFiles(builder, control.SourceFiles, "                        ");
        AppendSections(builder, control.Sections, "                        ");
        AppendRelated(builder, control.Related, "                        ");
        AppendWarnings(builder, control.Warnings, "                        ");
        builder.AppendLine("                        source,");
        builder.AppendLine($"                        {S(control.SnapshotId)},");
        builder.AppendLine($"                        {S(control.SnapshotSchemaVersion)},");
        builder.AppendLine($"                        {S(control.TargetVersion)},");
        builder.AppendLine($"                        {S(control.Language)}),");
    }

    private static void AppendIdentity(StringBuilder builder, ExtractedControlIdentityDocument identity, string indent)
    {
        builder.AppendLine($"{indent}new ControlDocumentIdentity(");
        builder.AppendLine($"{indent}    {S(identity.Id)},");
        builder.AppendLine($"{indent}    {S(identity.Name)},");
        builder.AppendLine($"{indent}    {S(identity.DisplayName)},");
        builder.AppendLine($"{indent}    {S(identity.CategoryId)},");
        builder.AppendLine($"{indent}    {S(identity.ProductId)},");
        builder.AppendLine($"{indent}    {S(identity.PackageId)},");
        builder.AppendLine($"{indent}    {S(identity.Namespace)},");
        builder.AppendLine($"{indent}    {S(identity.XamlNamespace)},");
        builder.AppendLine($"{indent}    {SN(identity.BaseType)},");
        builder.AppendLine($"{indent}    {S(identity.Status)},");
        builder.AppendLine($"{indent}    {B(identity.IsCommercial)}),");
    }

    private static void AppendUsage(StringBuilder builder, ExtractedControlUsageDocument usage, string indent)
    {
        builder.AppendLine($"{indent}new ControlUsageDocument(");
        builder.AppendLine($"{indent}    {S(usage.Summary)},");
        builder.AppendLine($"{indent}    {SA(usage.WhenToUse)},");
        builder.AppendLine($"{indent}    {SA(usage.WhenNotToUse)},");
        AppendSnippets(builder, usage.MinimalSnippets, $"{indent}    ", closeWithComma: false);
        builder.AppendLine($"{indent}),");
    }

    private static void AppendApiSurface(StringBuilder builder, ExtractedControlApiSurfaceDocument api, string indent)
    {
        builder.AppendLine($"{indent}new ControlApiSurfaceDocument(");
        builder.AppendLine($"{indent}    new ApiMemberDocument[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var member in api.Members)
        {
            builder.AppendLine($"{indent}        new({S(member.Name)}, {S(member.Kind)}, {S(member.DeclaringType)}, {S(member.Accessibility)}, {S(member.Signature)}, {SN(member.Type)}, {SN(member.DefaultValue)}, {S(member.ContractLevel)}, {S(member.Description)}, {S(member.SourcePath)}, {NI(member.SourceLine)}),");
        }

        builder.AppendLine($"{indent}    }},");
        builder.AppendLine($"{indent}    new ApiEventDocument[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var item in api.Events)
        {
            builder.AppendLine($"{indent}        new({S(item.Name)}, {S(item.Kind)}, {S(item.DeclaringType)}, {S(item.Accessibility)}, {S(item.Signature)}, {SN(item.RoutingStrategy)}, {SN(item.EventArgsType)}, {S(item.Description)}, {S(item.SourcePath)}, {NI(item.SourceLine)}),");
        }

        builder.AppendLine($"{indent}    }},");
        builder.AppendLine($"{indent}    new ApiInheritanceDocument[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var item in api.InheritedContracts)
        {
            builder.AppendLine($"{indent}        new({S(item.MemberName)}, {S(item.Kind)}, {S(item.DeclaringType)}, {S(item.Reason)}),");
        }

        builder.AppendLine($"{indent}    }},");
        builder.AppendLine($"{indent}    new ApiSurfaceDiagnostic[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var item in api.Diagnostics)
        {
            builder.AppendLine($"{indent}        new({S(item.Code)}, {S(item.Message)}, {S(item.Severity)}, {SN(item.MemberName)}),");
        }

        builder.AppendLine($"{indent}    }}),");
    }

    private static void AppendLogic(StringBuilder builder, ExtractedControlLogicStructureDocument logic, string indent)
    {
        builder.AppendLine($"{indent}new ControlLogicStructureDocument(");
        AppendLogicNodes(builder, logic.Inheritance, $"{indent}    ");
        AppendLogicNodes(builder, logic.PublicApiGroups, $"{indent}    ");
        AppendLogicFlows(builder, logic.StateFlows, $"{indent}    ");
        AppendLogicNodes(builder, logic.RuntimeCollaborators, $"{indent}    ");
        AppendLogicFlows(builder, logic.ThemeBridge, $"{indent}    ", closeWithComma: false);
        builder.AppendLine($"{indent}),");
    }

    private static void AppendLogicNodes(StringBuilder builder, IReadOnlyList<ExtractedLogicNodeDocument> nodes, string indent)
    {
        builder.AppendLine($"{indent}new LogicNodeDocument[]");
        builder.AppendLine($"{indent}{{");
        foreach (var node in nodes)
        {
            builder.AppendLine($"{indent}    new({S(node.Id)}, {S(node.Kind)}, {S(node.Label)}, {SN(node.Description)}, {SA(node.RelatedApis)}),");
        }

        builder.AppendLine($"{indent}}},");
    }

    private static void AppendLogicFlows(StringBuilder builder, IReadOnlyList<ExtractedLogicFlowDocument> flows, string indent, bool closeWithComma = true)
    {
        builder.AppendLine($"{indent}new LogicFlowDocument[]");
        builder.AppendLine($"{indent}{{");
        foreach (var flow in flows)
        {
            builder.AppendLine($"{indent}    new({S(flow.Id)}, {S(flow.Title)}, {SA(flow.Steps)}),");
        }

        builder.AppendLine(closeWithComma ? $"{indent}}}," : $"{indent}}}");
    }

    private static void AppendTheme(StringBuilder builder, ExtractedControlThemeDocument theme, string indent)
    {
        builder.AppendLine($"{indent}new ControlThemeDocument(");
        builder.AppendLine($"{indent}    {S(theme.TargetType)},");
        builder.AppendLine($"{indent}    new ThemeTemplateDocument[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var template in theme.Templates)
        {
            builder.AppendLine($"{indent}        new(");
            builder.AppendLine($"{indent}            {S(template.Id)},");
            builder.AppendLine($"{indent}            {S(template.SourceSelector)},");
            builder.AppendLine($"{indent}            {S(template.SourcePath)},");
            builder.AppendLine($"{indent}            {NI(template.SourceLine)},");
            AppendThemeNodes(builder, template.Roots, $"{indent}            ", closeWithComma: false);
            builder.AppendLine($"{indent}        ),");
        }

        builder.AppendLine($"{indent}    }},");
        builder.AppendLine($"{indent}    new ThemeSelectorGroupDocument[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var group in theme.SelectorGroups)
        {
            builder.AppendLine($"{indent}        new({S(group.Kind)}, {SA(group.Selectors)}, {S(group.Description)}),");
        }

        builder.AppendLine($"{indent}    }},");
        builder.AppendLine($"{indent}    new ThemeBindingDocument[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var binding in theme.TemplateBindings)
        {
            builder.AppendLine($"{indent}        new({S(binding.TargetNode)}, {S(binding.TargetProperty)}, {S(binding.SourceProperty)}),");
        }

        builder.AppendLine($"{indent}    }},");
        builder.AppendLine($"{indent}    new ThemeTokenUsageDocument[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var usage in theme.TokenUsages)
        {
            builder.AppendLine($"{indent}        new({S(usage.ResourceKind)}, {S(usage.TokenName)}, {S(usage.TargetSelector)}, {S(usage.TargetProperty)}),");
        }

        builder.AppendLine($"{indent}    }},");
        builder.AppendLine($"{indent}    new ThemeCustomizationBoundaryDocument[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var boundary in theme.CustomizationBoundaries)
        {
            builder.AppendLine($"{indent}        new({S(boundary.Target)}, {S(boundary.Stability)}, {S(boundary.Guidance)}),");
        }

        builder.AppendLine($"{indent}    }}),");
    }

    private static void AppendThemeNodes(StringBuilder builder, IReadOnlyList<ExtractedThemeNodeDocument> nodes, string indent, bool closeWithComma = true)
    {
        builder.AppendLine($"{indent}new ThemeNodeDocument[]");
        builder.AppendLine($"{indent}{{");
        foreach (var node in nodes)
        {
            builder.AppendLine($"{indent}    new({S(node.ElementType)}, {SN(node.Name)}, {SN(node.Stability)}, Array.Empty<ThemeNodeDocument>()),");
        }

        builder.AppendLine(closeWithComma ? $"{indent}}}," : $"{indent}}}");
    }

    private static void AppendExamples(StringBuilder builder, IReadOnlyList<ExtractedControlExampleDocument> examples, string indent)
    {
        builder.AppendLine($"{indent}new ControlExampleDocument[]");
        builder.AppendLine($"{indent}{{");
        foreach (var example in examples)
        {
            builder.AppendLine($"{indent}    new(");
            builder.AppendLine($"{indent}        {S(example.SourceKey)},");
            builder.AppendLine($"{indent}        {S(example.Title)},");
            builder.AppendLine($"{indent}        {S(example.Description)},");
            builder.AppendLine($"{indent}        {S(example.Kind)},");
            builder.AppendLine($"{indent}        {example.Priority},");
            builder.AppendLine($"{indent}        {SN(example.BadgeText)},");
            AppendSnippets(builder, example.Snippets, $"{indent}        ");
            builder.AppendLine($"{indent}        {S(example.SourcePath)},");
            builder.AppendLine($"{indent}        {NI(example.SourceLine)}),");
        }

        builder.AppendLine($"{indent}}},");
    }

    private static void AppendSnippets(StringBuilder builder, IReadOnlyList<ExtractedCodeSnippetDocument> snippets, string indent, bool closeWithComma = true)
    {
        builder.AppendLine($"{indent}new CodeSnippetDocument[]");
        builder.AppendLine($"{indent}{{");
        foreach (var snippet in snippets)
        {
            builder.AppendLine($"{indent}    new({S(snippet.Language)}, {S(snippet.Code)}, {SN(snippet.SourcePath)}, {NI(snippet.SourceLine)}),");
        }

        builder.AppendLine(closeWithComma ? $"{indent}}}," : $"{indent}}}");
    }

    private static void AppendTokens(StringBuilder builder, IReadOnlyList<ExtractedControlTokenDocument> tokens, string indent)
    {
        builder.AppendLine($"{indent}new ControlTokenDocument[]");
        builder.AppendLine($"{indent}{{");
        foreach (var token in tokens)
        {
            builder.AppendLine($"{indent}    new({S(token.Name)}, {S(token.Scope)}, {S(token.Status)}, {S(token.Description)}, {SA(token.ThemeUsage)}),");
        }

        builder.AppendLine($"{indent}}},");
    }

    private static void AppendSemanticParts(StringBuilder builder, IReadOnlyList<ExtractedControlSemanticPartDocument> parts, string indent)
    {
        builder.AppendLine($"{indent}new ControlSemanticPartDocument[]");
        builder.AppendLine($"{indent}{{");
        foreach (var part in parts)
        {
            builder.AppendLine($"{indent}    new({S(part.Part)}, {S(part.AtomUINode)}, {S(part.Responsibility)}, {SA(part.RelatedApis)}, {SA(part.RelatedTokens)}, {S(part.Stability)}),");
        }

        builder.AppendLine($"{indent}}},");
    }

    private static void AppendSourceFiles(StringBuilder builder, IReadOnlyList<ExtractedControlSourceFileDocument> files, string indent)
    {
        builder.AppendLine($"{indent}new ControlSourceFileDocument[]");
        builder.AppendLine($"{indent}{{");
        foreach (var file in files)
        {
            builder.AppendLine($"{indent}    new({S(file.Kind)}, {S(file.Path)}, {SN(file.Description)}),");
        }

        builder.AppendLine($"{indent}}},");
    }

    private static void AppendSections(StringBuilder builder, IReadOnlyList<ExtractedDocumentSectionContent> sections, string indent)
    {
        builder.AppendLine($"{indent}new DocumentSectionContent[]");
        builder.AppendLine($"{indent}{{");
        foreach (var section in sections)
        {
            builder.AppendLine($"{indent}    new({S(section.Id)}, {S(section.Title)}, {section.Order}, {S(section.Markdown)}, {SA(section.SourceKinds)}),");
        }

        builder.AppendLine($"{indent}}},");
    }

    private static void AppendRelated(StringBuilder builder, IReadOnlyList<ExtractedDocumentRelatedItem> related, string indent)
    {
        builder.AppendLine($"{indent}new DocumentRelatedItem[]");
        builder.AppendLine($"{indent}{{");
        foreach (var item in related)
        {
            builder.AppendLine($"{indent}    new({S(item.Kind)}, {S(item.Id)}, {S(item.Title)}, {S(item.Command)}),");
        }

        builder.AppendLine($"{indent}}},");
    }

    private static void AppendWarnings(StringBuilder builder, IReadOnlyList<ExtractedDocumentWarning> warnings, string indent)
    {
        builder.AppendLine($"{indent}new DocumentWarning[]");
        builder.AppendLine($"{indent}{{");
        foreach (var warning in warnings)
        {
            builder.AppendLine($"{indent}    new({S(warning.Code)}, {S(warning.Message)}, {SN(warning.Section)}),");
        }

        builder.AppendLine($"{indent}}},");
    }

    private static void AppendTopic(StringBuilder builder, ExtractedTopicDocument topic)
    {
        builder.AppendLine("                    new TopicDocument(");
        builder.AppendLine($"                        {S(topic.Id)},");
        builder.AppendLine($"                        {S(topic.Title)},");
        builder.AppendLine($"                        {S(topic.Language)},");
        AppendSections(builder, topic.Sections, "                        ");
        AppendRelated(builder, topic.Related, "                        ");
        AppendWarnings(builder, topic.Warnings, "                        ");
        builder.AppendLine("                        source,");
        builder.AppendLine($"                        {S(topic.SnapshotId)},");
        builder.AppendLine($"                        {S(topic.SnapshotSchemaVersion)},");
        builder.AppendLine($"                        {S(topic.TargetVersion)}),");
    }

    private static string S(string value)
    {
        return SymbolDisplayStringLiteral(value);
    }

    private static string SN(string? value)
    {
        return value is null ? "null" : S(value);
    }

    private static string SA(IReadOnlyList<string> values)
    {
        return values.Count == 0
            ? "Array.Empty<string>()"
            : $"new[] {{ {string.Join(", ", values.Select(S))} }}";
    }

    private static string NI(int? value)
    {
        return value is null ? "null" : value.Value.ToString();
    }

    private static string B(bool value)
    {
        return value ? "true" : "false";
    }

    private static string SymbolDisplayStringLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var ch in value)
        {
            builder.Append(ch switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\r' => "\\r",
                '\n' => "\\n",
                '\t' => "\\t",
                _ => ch
            });
        }

        builder.Append('"');
        return builder.ToString();
    }
}
