using System.Text;

namespace AtomUI.Cli.MetadataBuilder.SourceAnalysis.Writers;

internal static class PackageSnapshotCodeWriter
{
    public static void Write(ExtractedPackageSnapshot snapshot, string outputPath)
    {
        var directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(outputPath, Generate(snapshot), Encoding.UTF8);
    }

    private static string Generate(ExtractedPackageSnapshot snapshot)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace AtomUI.Cli.Hosting.Metadata;");
        builder.AppendLine();
        builder.AppendLine("internal static class BuiltInPackageSnapshotFactory");
        builder.AppendLine("{");
        builder.AppendLine("    public static IReadOnlyList<PackageSnapshot> Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        return");
        builder.AppendLine("        [");
        AppendSnapshot(builder, snapshot);
        builder.AppendLine("        ];");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendSnapshot(StringBuilder builder, ExtractedPackageSnapshot snapshot)
    {
        builder.AppendLine("            new PackageSnapshot(");
        builder.AppendLine($"                {S(snapshot.SchemaVersion)},");
        builder.AppendLine($"                {S(snapshot.SnapshotId)},");
        builder.AppendLine($"                {S(snapshot.TargetVersion)},");
        builder.AppendLine("                new PackageSourceIdentity(");
        builder.AppendLine($"                    {S(snapshot.Source.SourceRootConvention)},");
        builder.AppendLine($"                    {S(snapshot.Source.SourceRef)},");
        builder.AppendLine($"                    {S(snapshot.Source.SourceCommit)},");
        builder.AppendLine($"                    {S(snapshot.Source.GeneratedAt)}),");
        AppendProducts(builder, snapshot.Products);
        AppendPackages(builder, snapshot.Packages);
        AppendConflicts(builder, snapshot.Conflicts);
        AppendReplacements(builder, snapshot.Replacements);
        AppendDiagnostics(builder, snapshot.Diagnostics, closeSnapshot: true);
    }

    private static void AppendProducts(StringBuilder builder, IReadOnlyList<ExtractedPackageProduct> products)
    {
        builder.AppendLine("                [");
        foreach (var product in products)
        {
            builder.AppendLine($"                    new ProductPackageProfile({S(product.Id)}, {S(product.Name)}, {S(product.Description)}, {product.DisplayOrder}),");
        }

        builder.AppendLine("                ],");
    }

    private static void AppendPackages(StringBuilder builder, IReadOnlyList<ExtractedPackageDocument> packages)
    {
        builder.AppendLine("                [");
        foreach (var package in packages)
        {
            builder.AppendLine("                    new PackageDocument(");
            builder.AppendLine($"                        {S(package.Id)},");
            builder.AppendLine($"                        {S(package.ProductId)},");
            builder.AppendLine($"                        {S(package.Version)},");
            builder.AppendLine($"                        {S(package.Description)},");
            builder.AppendLine($"                        {S(package.PackageKind)},");
            builder.AppendLine($"                        {B(package.IsRequired)},");
            builder.AppendLine($"                        {B(package.IsOptional)},");
            builder.AppendLine($"                        {B(package.IsCommercial)},");
            builder.AppendLine($"                        {B(package.IsHidden)},");
            builder.AppendLine($"                        {SA(package.TargetFrameworks)},");
            builder.AppendLine($"                        {S(package.RootNamespace)},");
            builder.AppendLine($"                        {S(package.AssemblyName)},");
            AppendDependencies(builder, package.Dependencies, "                        ");
            AppendRegistration(builder, package.Registration, "                        ");
            AppendCompatibility(builder, package.Compatibility, "                        ");
            AppendControls(builder, package.Controls, "                        ");
            AppendSourceFiles(builder, package.SourceFiles, "                        ");
            AppendDiagnostics(builder, package.Diagnostics, "                        ", closePackage: true);
        }

        builder.AppendLine("                ],");
    }

    private static void AppendDependencies(StringBuilder builder, IReadOnlyList<ExtractedPackageDependency> dependencies, string indent)
    {
        builder.AppendLine($"{indent}[");
        foreach (var dependency in dependencies)
        {
            builder.AppendLine($"{indent}    new PackageDependencyDocument({S(dependency.Id)}, {S(dependency.Version)}, {S(dependency.Kind)}, {B(dependency.IsAtomUI)}),");
        }

        builder.AppendLine($"{indent}],");
    }

    private static void AppendRegistration(StringBuilder builder, IReadOnlyList<ExtractedPackageRegistration> registrations, string indent)
    {
        builder.AppendLine($"{indent}[");
        foreach (var registration in registrations)
        {
            builder.AppendLine($"{indent}    new PackageRegistrationDocument({S(registration.Name)}, {S(registration.Kind)}, {S(registration.Description)}, {SN(registration.SourcePath)}),");
        }

        builder.AppendLine($"{indent}],");
    }

    private static void AppendCompatibility(StringBuilder builder, ExtractedPackageCompatibility compatibility, string indent)
    {
        builder.AppendLine($"{indent}new PackageCompatibilityDocument(");
        builder.AppendLine($"{indent}    {SA(compatibility.TargetFrameworks)},");
        builder.AppendLine($"{indent}    {B(compatibility.IsAotCompatible)},");
        builder.AppendLine($"{indent}    {B(compatibility.IsTrimCompatible)},");
        builder.AppendLine($"{indent}    {SA(compatibility.Notes)}),");
    }

    private static void AppendControls(StringBuilder builder, IReadOnlyList<ExtractedPackageControl> controls, string indent)
    {
        builder.AppendLine($"{indent}[");
        foreach (var control in controls)
        {
            builder.AppendLine($"{indent}    new PackageControlDocument({S(control.Name)}, {S(control.DisplayName)}, {S(control.CategoryId)}, {S(control.CategoryName)}, {B(control.IsCommercial)}),");
        }

        builder.AppendLine($"{indent}],");
    }

    private static void AppendSourceFiles(StringBuilder builder, IReadOnlyList<ExtractedPackageSourceFile> sourceFiles, string indent)
    {
        builder.AppendLine($"{indent}[");
        foreach (var sourceFile in sourceFiles)
        {
            builder.AppendLine($"{indent}    new PackageSourceFileDocument({S(sourceFile.Kind)}, {S(sourceFile.Path)}),");
        }

        builder.AppendLine($"{indent}],");
    }

    private static void AppendConflicts(StringBuilder builder, IReadOnlyList<ExtractedPackageConflict> conflicts)
    {
        builder.AppendLine("                [");
        foreach (var conflict in conflicts)
        {
            builder.AppendLine($"                    new PackageConflictDocument({S(conflict.PackageId)}, {S(conflict.ConflictingPackageId)}, {S(conflict.Reason)}, {S(conflict.Severity)}),");
        }

        builder.AppendLine("                ],");
    }

    private static void AppendReplacements(StringBuilder builder, IReadOnlyList<ExtractedPackageReplacement> replacements)
    {
        builder.AppendLine("                [");
        foreach (var replacement in replacements)
        {
            builder.AppendLine($"                    new PackageReplacementDocument({S(replacement.PackageId)}, {S(replacement.ReplacementPackageId)}, {S(replacement.Reason)}),");
        }

        builder.AppendLine("                ],");
    }

    private static void AppendDiagnostics(
        StringBuilder builder,
        IReadOnlyList<ExtractedPackageDiagnostic> diagnostics,
        bool closeSnapshot)
    {
        builder.AppendLine("                [");
        foreach (var diagnostic in diagnostics)
        {
            builder.AppendLine($"                    new PackageDiagnostic({S(diagnostic.Code)}, {S(diagnostic.Severity)}, {S(diagnostic.Message)}, {SN(diagnostic.PackageId)}),");
        }

        builder.Append(closeSnapshot ? "                ])," : "                ],");
        builder.AppendLine();
    }

    private static void AppendDiagnostics(
        StringBuilder builder,
        IReadOnlyList<ExtractedPackageDiagnostic> diagnostics,
        string indent,
        bool closePackage)
    {
        builder.AppendLine($"{indent}[");
        foreach (var diagnostic in diagnostics)
        {
            builder.AppendLine($"{indent}    new PackageDiagnostic({S(diagnostic.Code)}, {S(diagnostic.Severity)}, {S(diagnostic.Message)}, {SN(diagnostic.PackageId)}),");
        }

        builder.Append(closePackage ? $"{indent}])," : $"{indent}],");
        builder.AppendLine();
    }

    private static string S(string value)
    {
        return SymbolDisplayStringLiteral(value);
    }

    private static string SN(string? value)
    {
        return value is null ? "null" : S(value);
    }

    private static string SA(IReadOnlyList<string> values)
    {
        return values.Count == 0
            ? "[]"
            : $"[{string.Join(", ", values.Select(S))}]";
    }

    private static string B(bool value)
    {
        return value ? "true" : "false";
    }

    private static string SymbolDisplayStringLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var ch in value)
        {
            builder.Append(ch switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\r' => "\\r",
                '\n' => "\\n",
                '\t' => "\\t",
                _ => ch
            });
        }

        builder.Append('"');
        return builder.ToString();
    }
}
