using System.Text;

namespace AtomUI.Cli.MetadataBuilder.SourceAnalysis.Writers;

internal static class SemanticSnapshotCodeWriter
{
    public static void Write(ExtractedSemanticSnapshot snapshot, string outputPath)
    {
        var directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(outputPath, Generate(snapshot), Encoding.UTF8);
    }

    private static string Generate(ExtractedSemanticSnapshot snapshot)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine();
        builder.AppendLine("namespace AtomUI.Cli.Hosting.Metadata;");
        builder.AppendLine();
        builder.AppendLine("internal static class BuiltInSemanticSnapshotFactory");
        builder.AppendLine("{");
        builder.AppendLine("    public static SemanticSnapshot Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        return new SemanticSnapshot(");
        builder.AppendLine($"            {S(snapshot.SchemaVersion)},");
        builder.AppendLine($"            {S(snapshot.SnapshotId)},");
        builder.AppendLine($"            {S(snapshot.TargetVersion)},");
        builder.AppendLine($"            {S(snapshot.SourceCommit)},");
        builder.AppendLine("            new SemanticControlDocument[]");
        builder.AppendLine("            {");
        foreach (var control in snapshot.Controls)
        {
            AppendControl(builder, control);
        }

        builder.AppendLine("            },");
        builder.AppendLine("            new SemanticDiagnosticDocument[]");
        builder.AppendLine("            {");
        foreach (var diagnostic in snapshot.Diagnostics)
        {
            builder.AppendLine($"                new({S(diagnostic.Code)}, {S(diagnostic.Severity)}, {S(diagnostic.Message)}),");
        }

        builder.AppendLine("            });");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendControl(StringBuilder builder, ExtractedSemanticControl control)
    {
        builder.AppendLine("                new SemanticControlDocument(");
        builder.AppendLine($"                    {S(control.Name)},");
        builder.AppendLine("                    new SemanticPartDocument[]");
        builder.AppendLine("                    {");
        foreach (var part in control.Parts)
        {
            builder.AppendLine("                        new(");
            builder.AppendLine($"                            {S(part.Name)},");
            builder.AppendLine($"                            {S(part.NodeType)},");
            builder.AppendLine($"                            {S(part.Description)},");
            builder.AppendLine($"                            {SA(part.BoundApis)},");
            builder.AppendLine($"                            {SA(part.PseudoClasses)},");
            builder.AppendLine($"                            {SA(part.TokenUsages)},");
            builder.AppendLine($"                            new SemanticSourceDocument({S(part.SourcePath)}, {NI(part.SourceLine)})),");
        }

        builder.AppendLine("                    },");
        builder.AppendLine("                    new SemanticPseudoClassDocument[]");
        builder.AppendLine("                    {");
        foreach (var pseudoClass in control.PseudoClasses)
        {
            builder.AppendLine("                        new(");
            builder.AppendLine($"                            {S(pseudoClass.Name)},");
            builder.AppendLine($"                            {S(pseudoClass.Description)},");
            builder.AppendLine($"                            {SA(pseudoClass.BoundApis)},");
            builder.AppendLine($"                            {SA(pseudoClass.Selectors)},");
            builder.AppendLine($"                            new SemanticSourceDocument({S(pseudoClass.SourcePath)}, {NI(pseudoClass.SourceLine)})),");
        }

        builder.AppendLine("                    },");
        builder.AppendLine("                    new SemanticThemeTemplateDocument[]");
        builder.AppendLine("                    {");
        foreach (var template in control.Templates)
        {
            AppendTemplate(builder, template);
        }

        builder.AppendLine("                    }),");
    }

    private static void AppendTemplate(StringBuilder builder, ExtractedSemanticThemeTemplate template)
    {
        builder.AppendLine("                        new(");
        builder.AppendLine($"                            {S(template.ThemeName)},");
        builder.AppendLine($"                            {S(template.Selector)},");
        builder.AppendLine($"                            new SemanticSourceDocument({S(template.SourcePath)}, {NI(template.SourceLine)}),");
        builder.AppendLine("                            new SemanticThemeNodeDocument[]");
        builder.AppendLine("                            {");
        foreach (var root in template.Roots)
        {
            AppendNode(builder, root, 32);
        }

        builder.AppendLine("                            }),");
    }

    private static void AppendNode(StringBuilder builder, ExtractedSemanticThemeNode node, int indent)
    {
        var padding = new string(' ', indent);
        builder.AppendLine($"{padding}new(");
        builder.AppendLine($"{padding}    {S(node.ElementType)},");
        builder.AppendLine($"{padding}    {SN(node.Name)},");
        builder.AppendLine($"{padding}    new SemanticThemeNodeDocument[]");
        builder.AppendLine($"{padding}    {{");
        foreach (var child in node.Children)
        {
            AppendNode(builder, child, indent + 8);
        }

        builder.AppendLine($"{padding}    }}),");
    }

    private static string S(string value)
    {
        return SymbolDisplayStringLiteral(value);
    }

    private static string SA(IReadOnlyList<string> values)
    {
        return values.Count == 0
            ? "Array.Empty<string>()"
            : $"new[] {{ {string.Join(", ", values.Select(S))} }}";
    }

    private static string SN(string? value)
    {
        return value is null ? "null" : S(value);
    }

    private static string NI(int? value)
    {
        return value is null ? "null" : value.Value.ToString();
    }

    private static string SymbolDisplayStringLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var ch in value)
        {
            builder.Append(ch switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\r' => "\\r",
                '\n' => "\\n",
                '\t' => "\\t",
                _ => ch
            });
        }

        builder.Append('"');
        return builder.ToString();
    }
}
