<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>AtomUI.Cli.MetadataBuilder</AssemblyName>
    <RootNamespace>AtomUI.Cli.MetadataBuilder</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>
</Project>
