using System.Text;

namespace AtomUI.Cli.MetadataBuilder;

internal static class TokenSnapshotCodeWriter
{
    public static void Write(ExtractedTokenSnapshot snapshot, string outputPath)
    {
        var directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(outputPath, Generate(snapshot), Encoding.UTF8);
    }

    private static string Generate(ExtractedTokenSnapshot snapshot)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine();
        builder.AppendLine("namespace AtomUI.Cli.Hosting.Metadata;");
        builder.AppendLine();
        builder.AppendLine("internal static class BuiltInTokenSnapshotFactory");
        builder.AppendLine("{");
        builder.AppendLine("    public static TokenSnapshot Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        var products = new TokenProductDocument[]");
        builder.AppendLine("        {");
        foreach (var product in snapshot.Products)
        {
            builder.AppendLine($"            new({S(product.Id)}, {S(product.Name)}, {S(product.PackageId)}, {B(product.IsCommercial)}),");
        }
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        var shared = new TokenDocument[]");
        builder.AppendLine("        {");
        foreach (var token in snapshot.SharedTokens)
        {
            builder.AppendLine($"            Shared({S(token.Name)}, {S(token.Kind)}, {S(token.Category)}, {S(token.Type)}, {SN(token.DefaultValue)}, {S(token.Description)}, {S(token.SourcePath)}, {token.SourceLine}),");
        }
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        var controls = new ControlTokenSetDocument[]");
        builder.AppendLine("        {");
        foreach (var control in snapshot.ControlTokenSets)
        {
            AppendControlTokenSet(builder, control);
        }
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        return new TokenSnapshot(");
        builder.AppendLine($"            {S(snapshot.SchemaVersion)},");
        builder.AppendLine($"            {S(snapshot.SnapshotId)},");
        builder.AppendLine($"            {S(snapshot.TargetVersion)},");
        builder.AppendLine($"            {S(snapshot.SourceCommit)},");
        builder.AppendLine("            products,");
        builder.AppendLine("            shared,");
        builder.AppendLine("            controls,");
        builder.AppendLine("            controls.SelectMany(control => control.Tokens).SelectMany(token => token.Dependencies).ToArray(),");
        builder.AppendLine("            new TokenDiagnosticDocument[]");
        builder.AppendLine("            {");
        foreach (var diagnostic in snapshot.Diagnostics)
        {
            builder.AppendLine($"                new({S(diagnostic.Code)}, {S(diagnostic.Severity)}, {S(diagnostic.Message)}),");
        }
        builder.AppendLine("            });");
        builder.AppendLine("    }");
        builder.AppendLine();
        AppendHelpers(builder);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendControlTokenSet(StringBuilder builder, ExtractedControlTokenSet control)
    {
        builder.AppendLine("            ControlSet(");
        builder.AppendLine($"                {S(control.ControlName)},");
        builder.AppendLine($"                {S(control.TokenId)},");
        builder.AppendLine($"                {S(control.TokenTypeName)},");
        builder.AppendLine($"                {S(control.ScopeProviderName)},");
        builder.AppendLine($"                {S(control.PackageId)},");
        builder.AppendLine($"                {S(control.ProductId)},");
        builder.AppendLine($"                {B(control.IsCommercial)},");
        builder.AppendLine($"                {SA(control.RegisteredControls)},");
        builder.AppendLine("                new TokenDocument[]");
        builder.AppendLine("                {");
        foreach (var token in control.Tokens)
        {
            AppendControlToken(builder, token);
        }
        builder.AppendLine("                }),");
    }

    private static void AppendControlToken(StringBuilder builder, ExtractedControlToken token)
    {
        builder.AppendLine("                    ControlToken(");
        builder.AppendLine($"                        {S(token.ControlName)},");
        builder.AppendLine($"                        {S(token.Name)},");
        builder.AppendLine($"                        {S(token.Category)},");
        builder.AppendLine($"                        {S(token.Type)},");
        builder.AppendLine($"                        {SN(token.DefaultValue)},");
        builder.AppendLine($"                        {S(token.Description)},");
        builder.AppendLine($"                        {S(token.TokenTypeName)},");
        builder.AppendLine($"                        {S(token.SourcePath)},");
        builder.AppendLine($"                        {token.SourceLine},");
        builder.AppendLine($"                        {SN(token.GeneratedPath)},");
        builder.AppendLine($"                        {SA(token.Dependencies)},");
        builder.AppendLine("                        new TokenUsageDocument[]");
        builder.AppendLine("                        {");
        foreach (var usage in token.Usages)
        {
            builder.AppendLine($"                            new({S(usage.ThemeName)}, {S(usage.Selector)}, {S(usage.TargetProperty)}, {SN(usage.TargetNode)}, {S(usage.ResourceExpression)}, {S(usage.SourcePath)}, {usage.SourceLine}),");
        }
        builder.AppendLine("                        },");
        builder.AppendLine($"                        {S(token.CustomizationLevel)}),");
    }

    private static void AppendHelpers(StringBuilder builder)
    {
        builder.AppendLine("    private static ControlTokenSetDocument ControlSet(");
        builder.AppendLine("        string controlName,");
        builder.AppendLine("        string tokenId,");
        builder.AppendLine("        string tokenTypeName,");
        builder.AppendLine("        string scopeProviderName,");
        builder.AppendLine("        string packageId,");
        builder.AppendLine("        string productId,");
        builder.AppendLine("        bool isCommercial,");
        builder.AppendLine("        string[] registeredControls,");
        builder.AppendLine("        TokenDocument[] tokens)");
        builder.AppendLine("    {");
        builder.AppendLine("        return new ControlTokenSetDocument(");
        builder.AppendLine("            controlName,");
        builder.AppendLine("            tokenId,");
        builder.AppendLine("            tokenTypeName,");
        builder.AppendLine("            scopeProviderName,");
        builder.AppendLine("            packageId,");
        builder.AppendLine("            productId,");
        builder.AppendLine("            isCommercial,");
        builder.AppendLine("            registeredControls,");
        builder.AppendLine("            tokens,");
        builder.AppendLine("            tokens.SelectMany(token => token.Dependencies.Select(edge => edge.From))");
        builder.AppendLine("                .Where(dependency => dependency.StartsWith(\"Shared.\", StringComparison.Ordinal))");
        builder.AppendLine("                .Distinct(StringComparer.Ordinal)");
        builder.AppendLine("                .OrderBy(dependency => dependency, StringComparer.Ordinal)");
        builder.AppendLine("                .ToArray(),");
        builder.AppendLine("            tokens.SelectMany(token => token.Usages).ToArray());");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static TokenDocument Shared(");
        builder.AppendLine("        string name,");
        builder.AppendLine("        string kind,");
        builder.AppendLine("        string category,");
        builder.AppendLine("        string type,");
        builder.AppendLine("        string? defaultValue,");
        builder.AppendLine("        string description,");
        builder.AppendLine("        string sourcePath,");
        builder.AppendLine("        int sourceLine)");
        builder.AppendLine("    {");
        builder.AppendLine("        return new TokenDocument(");
        builder.AppendLine("            $\"Shared.{name}\",");
        builder.AppendLine("            name,");
        builder.AppendLine("            \"shared\",");
        builder.AppendLine("            kind,");
        builder.AppendLine("            category,");
        builder.AppendLine("            type,");
        builder.AppendLine("            defaultValue,");
        builder.AppendLine("            description,");
        builder.AppendLine("            new TokenResourceDocument(");
        builder.AppendLine("                \"SharedTokenResource\",");
        builder.AppendLine("                $\"SharedTokenKind.{name}\",");
        builder.AppendLine("                $\"{{atom:SharedTokenResource {name}}}\",");
        builder.AppendLine("                $\"Value=\\\"{{atom:SharedTokenResource {name}}}\\\"\",");
        builder.AppendLine("                \"generated-public\"),");
        builder.AppendLine("            new TokenSourceDocument(sourcePath, sourceLine, null, null),");
        builder.AppendLine("            string.IsNullOrWhiteSpace(defaultValue)");
        builder.AppendLine("                ? Array.Empty<TokenValueVariantDocument>()");
        builder.AppendLine("                : new[] { new TokenValueVariantDocument(\"default\", defaultValue, \"source-initializer\") },");
        builder.AppendLine("            Array.Empty<TokenGraphEdgeDocument>(),");
        builder.AppendLine("            Array.Empty<TokenUsageDocument>(),");
        builder.AppendLine("            new TokenCustomizationDocument(\"public-stable\", \"Recommended shared theme customization token.\", Array.Empty<string>()));");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static TokenDocument ControlToken(");
        builder.AppendLine("        string control,");
        builder.AppendLine("        string name,");
        builder.AppendLine("        string category,");
        builder.AppendLine("        string type,");
        builder.AppendLine("        string? defaultValue,");
        builder.AppendLine("        string description,");
        builder.AppendLine("        string tokenType,");
        builder.AppendLine("        string sourcePath,");
        builder.AppendLine("        int sourceLine,");
        builder.AppendLine("        string? generatedPath,");
        builder.AppendLine("        string[] dependencies,");
        builder.AppendLine("        TokenUsageDocument[] usages,");
        builder.AppendLine("        string customizationLevel)");
        builder.AppendLine("    {");
        builder.AppendLine("        var tokenId = $\"{control}.{name}\";");
        builder.AppendLine("        return new TokenDocument(");
        builder.AppendLine("            tokenId,");
        builder.AppendLine("            name,");
        builder.AppendLine("            \"control\",");
        builder.AppendLine("            \"control\",");
        builder.AppendLine("            category,");
        builder.AppendLine("            type,");
        builder.AppendLine("            defaultValue,");
        builder.AppendLine("            description,");
        builder.AppendLine("            new TokenResourceDocument(");
        builder.AppendLine("                $\"{control}TokenResource\",");
        builder.AppendLine("                $\"{control}TokenKind.{name}\",");
        builder.AppendLine("                $\"{{atom:{control}TokenResource {name}}}\",");
        builder.AppendLine("                $\"Value=\\\"{{atom:{control}TokenResource {name}}}\\\"\",");
        builder.AppendLine("                \"generated-public\"),");
        builder.AppendLine("            new TokenSourceDocument(sourcePath, sourceLine, generatedPath, null),");
        builder.AppendLine("            string.IsNullOrWhiteSpace(defaultValue)");
        builder.AppendLine("                ? new[] { new TokenValueVariantDocument(\"default\", null, $\"{tokenType}.CalculateTokenValues\") }");
        builder.AppendLine("                : new[] { new TokenValueVariantDocument(\"default\", defaultValue, \"source-initializer\") },");
        builder.AppendLine("            dependencies.Select(dependency => new TokenGraphEdgeDocument(dependency, tokenId, \"derives-from\", $\"{tokenId} derives from {dependency}.\")).ToArray(),");
        builder.AppendLine("            usages,");
        builder.AppendLine("            new TokenCustomizationDocument(");
        builder.AppendLine("                customizationLevel,");
        builder.AppendLine("                customizationLevel.Equals(\"public-stable\", StringComparison.Ordinal)");
        builder.AppendLine("                    ? \"Recommended as a stable control theme customization token.\"");
        builder.AppendLine("                    : \"Generated resource key. Use when the control theme contract requires it.\",");
        builder.AppendLine("                Array.Empty<string>()));");
        builder.AppendLine("    }");
    }

    private static string S(string value)
    {
        return SymbolDisplayStringLiteral(value);
    }

    private static string SN(string? value)
    {
        return value is null ? "null" : S(value);
    }

    private static string SA(IReadOnlyList<string> values)
    {
        return values.Count == 0
            ? "Array.Empty<string>()"
            : $"new[] {{ {string.Join(", ", values.Select(S))} }}";
    }

    private static string B(bool value)
    {
        return value ? "true" : "false";
    }

    private static string SymbolDisplayStringLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var ch in value)
        {
            builder.Append(ch switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\r' => "\\r",
                '\n' => "\\n",
                '\t' => "\\t",
                _ => ch
            });
        }

        builder.Append('"');
        return builder.ToString();
    }
}
